### ISSUE TITLE
include the saved passphrase for public keys

### ISSUE THREAD

**Issue by cwhitten** [dockito/vault#2]
I'm inspired by this tool packaging keys into the container without any trace of the keys existing in it, but the case where a passphrase for the public key is required when being used (against github, for example) a workaround has yet to pop-up. Any thoughts?

**Comment by maxclaus** [comment]
I think this is quite harder to solve. I quick brainstorm I had in few minutes thinking about it:
- One idea to solve it would be reading the passphrase from a file also in `.ssh` directory. But this is even worse than using the ssh with no passphrase. Because your passphrase would be stored in plain text.
- Another solution a bit better would be using a prompt during the `ONVAULT` command asking the passphrase. I think this would work pretty good in development environment. But in production and other private environments this would be up to who is using it how to provide this passphrase to the `ONVAULT` prompt. We usually use jenkins to build our production images, so it would be pretty easy to set an environment variable with the passphrase. But again, maybe this could be a bit insecurity storing passphrase in environment variables, at least I usually see command lines complaining about it.

**Comment by pirelenito** [comment]
I can't see an available solution to this problem. I'm therefore closing this issue. :+1:

**Comment by Vanuan** [comment]
We don't use passhprase on jenkins, because anybody who's able to execute custom code in jenkins build is able to access its filesystem and environment.
But for development machines, it's risky to have a private key in open text.

I was hoping that Vault could help me to manage all secrets transparently:
A developer would provide some authorization to a global Vault instance, and depending on user authorization, a temporary key without passphrase would be fetched. Jenkins would fetch its key accordingly.

Currently, I don't see how Dockito Vault is helping here. I'm able to mount an ~/.ssh directory myself.

**Comment by Vanuan** [comment]
To solve passphrase issue specifically, one could use ssh-agent forwarding: https://github.com/docker/docker/issues/6396
This would be a use case for dockito vault.
