### ISSUE TITLE
usage: docker for mac

### ISSUE THREAD

**Issue by rosskevin** [dockito/vault#26]
I looked through past issues and didn't find it, is there a simple usage for the docker for mac host?

``` bash
$ ifconfig docker0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}'
ifconfig: interface docker0 does not exist

$ docker -v
Docker version 1.12.1, build 6f9534c
```

**Comment by maxclaus** [comment]
I have been using docker on mac as well. I could not find out an easy way to discover the Docker IP interface by command line. Seems the docker interface is not running in the host. But it is running in a VM. So is not possible to bind the container port to the Docker IP gateway from your host machine.

I can think on 2 approaches to make it work on mac.

1) Bind the vault port to your host machine ip.

```
HOST_IP="$(ifconfig en1 | grep "inet " | cut -d " " -f2)"
docker run -d --name vault -p $HOST_IP:14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault:latest
```

Then set an environment variable `VAULT_HOST` with your `HOST_IP` wherever container you need to run the `ONVAULT` script.

2) Or what I have done is just running the vault container without bind to a specific IP. So its bind to 0.0.0.0 by default. 

```
docker run -d --name vault -p 14242:3000 -v ~/.ssh:/vault/.ssh dockito/vault:latest
```

By doing that anyone in your network could have access to the vault service. So ensure that port is not open to external machines. Once you don't set the bind to a specific IP and do not set custom environment variables for the `ONVAULT` script you should get it working. Because the `ONVAULT` script has already the logic to find out the current docker IP gateway.

I prefer the second approach because I don't have to set custom configurations to all containers using `ONVAULT`. But it could be less safe than the first approach if you don't have a firewall.
