### ISSUE TITLE
~/.npmrc - using a private npm registry inside docker build

### ISSUE THREAD

**Issue by rosskevin** [dockito/vault#27]
Analogous to the private key approach (which we use for some npm repos), we have a similar need for `~/.npmrc` which stores an access token for npmjs.com and we need it to be present and deleted after an `ONVAULT` command.

Is this possible with the current script?  Has anyone else solved this?

EDIT: [more info](https://docs.npmjs.com/private-modules/docker-and-private-modules), but I'd like to use dockito since I already have it setup and the process would be the same.

**Comment by maxclaus** [comment]
The current approach is focused on ssh files. But since the vault will copy the whole `.ssh` directory to inside the container it may work with other files as well if you keep them inside `.ssh` directory. So it will be copied and removed automatically by the vault script. This looks ugly because is not the "suggested" usage for the vault. But I guess you could still use it as a workaround.
